drop
all objects;
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR                                 NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TYPE booking_status AS ENUM ('WAITING','APPROVE','REJECTED','CANCELED');

CREATE TABLE bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_booking  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_of_booking TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id        BIGINT                                  NOT NULL,
    booker_id      BIGINT                                  NOT NULL,
    status         booking_status                          NOT NULL
);

ALTER TABLE items
    ADD CONSTRAINT "fk_item_user_id" FOREIGN KEY (owner_id)
        REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT "fk_booking_item_id" FOREIGN KEY (item_id)
        REFERENCES items (id) ON DELETE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT "fk_booking_user_id" FOREIGN KEY (booker_id)
        REFERENCES users (id) ON DELETE CASCADE;